### PR TITLE
Relax magic numbers, error object-curly, error react stylings

### LINKED ISSUE #8: Proposing changes to default configuration
We can use this issue as a place to collect feedback on the current configuration of eslint-rules before being released@1.0

**Note from Roemer**: We're laserlight focused on getting `v1.0.0` out, so any issues getting bogged down in bikeshedding (particularly if code-style-only), will be captured in a post-`initial-release` issue with @kenwheeler making an interim executive decision for current release).

### PR DESCRIPTION
**Pull request by kylecesmat**
This changes:
- Make magic numbers less magic `"no-magic-numbers": ["error", { "ignore": [-1, 0, 1] }]`
- Always enforce `"object-curly-spacing"`
- React changes below

```
"react/no-multi-comp": 2
"react/no-string-refs": 2,
"react/sort-comp": 2,
"sort-prop-types": 2,
```

closes #8 

cc @kenwheeler @ryan-roemer @exogen @baer

### CODE REVIEW

**Comment by kenwheeler** [comment]
👍

**Comment by exogen** [comment]
Re: `no-string-refs`, should we should have a documented convention for how we store & name refs? String refs are just so damn convenient in that they give you both of those things automatically. e.g. is our convention "leading underscore, stick it on `this`" like in the React docs?  `(node) => { this._input = node }` (I personally get peeved whenever I need to use a callback `ref` and make this decision, it just looks ugly to me.)

**Comment by kenwheeler** [comment]
String refs are sooo convenient, but also on the chopping block for deprecation. Better to nip that in the bud. I'm impartial on underscore prefixing, but a stated convention would be nice to have.

**Comment by kylecesmat** [comment]
@exogen  - I do agree these should be documented, I'm going to agree with Ken that this is a good pattern and we can either override on a project-basis or patch this if it causes frustration.

**Pull request merged**
