### PR TITLE
Add release PR

### PR DESCRIPTION
**Pull request by baer**
Release 2.1.0

@ryan-roemer @kylecesmat

### CODE REVIEW

**Comment by ryan-roemer** [comment]
I think we need to make it major. This will break all Node `0.10` and `0.12` installs which means, e.g., that a lot of build matrices will just straight fail for unrelated reasons if it's minor.

(for example, we broke our **own** CI in PRs adding this stuff in 😉  )

**Comment by baer** [comment]
In that case, is this worth a release? We'll need to do another major at 4.x and another major when we update our rules.

**Comment by ryan-roemer** [comment]
Are there rule changes in 4.x? or other changes that may take us time to sort out?

This is otherwise ready to ship, so may be worth doing it to have something in the interim if we don't have collective bandwidth to get to the 4.x upgrade after it's released.... (?)

**Comment by kylecesmat** [comment]
This should be a *major* release because of the node breakages & that we are now depending on eslint@3.

The eslint@4 release is in alpha currently, and we'd likely punt on upgrading our ruleset until later ecosystem maturity? It seems like we're pretty conservative with this ruleset..

Also, our versioning will line up nicely with the eslint versions if we go to 3.x now :P

**Comment by baer** [comment]
Looks like the LOE for migrating to 4 for this project will be pretty low.
There is only one new rule but there are some existing rules that will be
enforced slightly differently. They've already got 3 alphas and it looks
like there isn't much left for them to do. I'm unafraid of bumping major
revs so I'll go for it.

https://github.com/eslint/eslint/projects/3
http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0

**Review by ryan-roemer — APPROVED** [review]

**Pull request merged**
